sudo: required
services:
  - docker

before_install:
  - docker build -t debasishmisra/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true debasishmisra/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react" #app_name
  env: "DockerReact-env" #environment_name
  bucket_name: "elasticbeanstalk-us-east-1-170629694778" #available in s3
  bucket_path: "docker-react" #equal to app_name
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
